version: '3.1'
services:
  API:
    image: "safari-webstore:latest"
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=563248
      - POSTGRES_USER=postgres
      - POSTGRES_DB=MyBlog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5